INSERT INTO AvailableDrones (DroneSerial, DroneModel, DroneWeightLimit, DroneBatteryCapacity, DroneState) VALUES ('DRONE01', 'Lightweight', 500, 100, 'IDLE');
INSERT INTO AvailableDrones (DroneSerial, DroneModel, DroneWeightLimit, DroneBatteryCapacity, DroneState) VALUES ('DRONE02', 'Lightweight', 500, 100, 'IDLE');
INSERT INTO AvailableDrones (DroneSerial, DroneModel, DroneWeightLimit, DroneBatteryCapacity, DroneState) VALUES ('DRONE03', 'Lightweight', 500, 100, 'IDLE');
INSERT INTO AvailableDrones (DroneSerial, DroneModel, DroneWeightLimit, DroneBatteryCapacity, DroneState) VALUES ('DRONE04', 'Middleweight', 500, 100, 'IDLE');
INSERT INTO AvailableDrones (DroneSerial, DroneModel, DroneWeightLimit, DroneBatteryCapacity, DroneState) VALUES ('DRONE05', 'Middleweight', 500, 100, 'IDLE');
INSERT INTO AvailableDrones (DroneSerial, DroneModel, DroneWeightLimit, DroneBatteryCapacity, DroneState) VALUES ('DRONE06', 'Middleweight', 500, 100, 'IDLE');
INSERT INTO AvailableDrones (DroneSerial, DroneModel, DroneWeightLimit, DroneBatteryCapacity, DroneState) VALUES ('DRONE07', 'Cruiserweight', 500, 100, 'IDLE');
INSERT INTO AvailableDrones (DroneSerial, DroneModel, DroneWeightLimit, DroneBatteryCapacity, DroneState) VALUES ('DRONE08', 'Cruiserweight', 500, 100, 'IDLE');
INSERT INTO AvailableDrones (DroneSerial, DroneModel, DroneWeightLimit, DroneBatteryCapacity, DroneState) VALUES ('DRONE09', 'Heavyweight', 500, 100, 'IDLE');
INSERT INTO AvailableDrones (DroneSerial, DroneModel, DroneWeightLimit, DroneBatteryCapacity, DroneState) VALUES ('DRONE10', 'Heavyweight', 500, 100, 'IDLE');
INSERT INTO Medication (MedicationCode, MedicationName, MedicationWeight, MedicationImageURL) VALUES ('MED01', 'Med01', 40, 'https://domain.com/path-to-resource-1');
INSERT INTO Medication (MedicationCode, MedicationName, MedicationWeight, MedicationImageURL) VALUES ('MED02', 'Med02', 20, 'https://domain.com/path-to-resource-2');
INSERT INTO Medication (MedicationCode, MedicationName, MedicationWeight, MedicationImageURL) VALUES ('MED03', 'Med03', 10, 'https://domain.com/path-to-resource-3');