DROP TABLE IF EXISTS AvailableDrones;

CREATE TABLE AvailableDrones(
	id INT AUTO_INCREMENT PRIMARY KEY,
	DroneSerial VARCHAR(100) NOT NULL,
	DroneModel VARCHAR(13) NOT NULL,
	DroneWeightLimit INT NOT NULL,
	DroneBatteryCapacity INT NOT NULL,
	DroneState VARCHAR(10) NOT NULL,
	LoadID VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS DispatchedDrones;

CREATE TABLE DispatchedDrones(
	id INT AUTO_INCREMENT PRIMARY KEY,
	DroneSerial VARCHAR(100) NOT NULL,
	DroneModel VARCHAR(13) NOT NULL,
	DroneWeightLimit  INT NOT NULL,
	DroneBatteryCapacity INT NOT NULL,
	DroneState VARCHAR(10) NOT NULL,
	LoadID VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS LoadedMedications;

CREATE TABLE LoadedMedications(
	id INT AUTO_INCREMENT PRIMARY KEY,
	MedicationCode VARCHAR(250) NOT NULL,
	MedicationName VARCHAR(250) NOT NULL,
	MedicationWeight INT NOT NULL,
	MedicationImageURL VARCHAR(250) NOT NULL,
	DroneSerial VARCHAR(100) NOT NULL,
	LoadID VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS Medication;

CREATE TABLE Medication(
	id INT AUTO_INCREMENT PRIMARY KEY,
	MedicationCode VARCHAR(250) NOT NULL,
	MedicationName VARCHAR(250) NOT NULL,
	MedicationWeight INT NOT NULL,
	MedicationImageURL VARCHAR(250) NOT NULL,
	DroneSerial VARCHAR(100) DEFAULT NULL,
	LoadID VARCHAR(250) DEFAULT NULL
);


